'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AutoTurnOff.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close application.
        '''</summary>
        Friend ReadOnly Property NtfMainClose() As String
            Get
                Return ResourceManager.GetString("NtfMainClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration.
        '''</summary>
        Friend ReadOnly Property NtfMainConfig() As String
            Get
                Return ResourceManager.GetString("NtfMainConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend ReadOnly Property NtfMainOpen() As String
            Get
                Return ResourceManager.GetString("NtfMainOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fuck u.
        '''</summary>
        Friend ReadOnly Property StringTest() As String
            Get
                Return ResourceManager.GetString("StringTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel all scheduled shutdowns.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdown_BtnCancelar_Text() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdown_BtnCancelar_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedule shutdown.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdown_BtnSetShutdownTimeout_Text() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdown_BtnSetShutdownTimeout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Movie time:.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdown_Label1_Text() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdown_Label1_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hours and.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdown_Label2_Text() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdown_Label2_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutes.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdown_Label3_Text() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdown_Label3_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Movie Auto Shutdown.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdown_Title() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdown_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The minimun time to schedule is 1 minute.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdownMinimunTimeNotExpected() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdownMinimunTimeNotExpected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid time.
        '''</summary>
        Friend ReadOnly Property WndAutoShutdownMinimunTimeNotExpectedTitle() As String
            Get
                Return ResourceManager.GetString("WndAutoShutdownMinimunTimeNotExpectedTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Movie Auto Turn Off Notification.
        '''</summary>
        Friend ReadOnly Property WndSplashscreen_NtfMain_Text() As String
            Get
                Return ResourceManager.GetString("WndSplashscreen_NtfMain_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure?.
        '''</summary>
        Friend ReadOnly Property WndSplashscreen_TsmClose_Click_Text() As String
            Get
                Return ResourceManager.GetString("WndSplashscreen_TsmClose_Click_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property WndSplashscreen_TsmClose_Click_Title() As String
            Get
                Return ResourceManager.GetString("WndSplashscreen_TsmClose_Click_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Post Movie Auto Turn Off....
        '''</summary>
        Friend ReadOnly Property WndSplashscreenLoadingMessage() As String
            Get
                Return ResourceManager.GetString("WndSplashscreenLoadingMessage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
